POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im91c3VmYWxpIiwiaWQiOiI1Zjg4YmMwMzRhMzQxMTUwYzRiYmFiZDEiLCJpYXQiOjE2MDI3OTY1NTd9.yg08RBZlON7b1UfvrT1tJCvvBPx1s6Hn7uaj12HGKK4

{
    "title" : "ami abo",
    "author": "beta",
    "likes" : 4
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im91c3VmYWxpIiwiaWQiOiI1Zjg4YmMwMzRhMzQxMTUwYzRiYmFiZDEiLCJpYXQiOjE2MDI3OTY1NTd9.yg08RBZlON7b1UfvrT1tJCvvBPx1s6Hn7uaj12HGKK4