POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "asd",
    "name" : "temp test",
    "password" : "asd"
}

# {
#     "username" : "ousufali",
#     "name" : "Yousuf Ali",
#     "password" : "1234"
# }